package test2;

public class trycatchpract {

	public static void main(String[] args) {
		
		//System.out.println("Hello");
		//System.out.println(5/0);
		//System.out.println("bye");
		
		
		//System.out.println("Hello");
	
		//try {
		//	int divideByZero = (5/0);
			//System.out.println("Rest of code in try block");
		//	System.out.println("Rest of code in try block2");
		//	System.out.println("Rest of code in try block3");
		//	System.out.println("Rest of code in try block4");	
		}
		//catch(ArithmeticException e) {	
		
		//System.out.println(e.getMessage());
			
		//}
		//System.out.println("bye bye");
		
		
		System.out.println("Define a array with values");
		int []numbers = {10,20,30,40};
		
		try {
			
			System.out.println(numbers[0]);
			System.out.println(numbers[5]);
		}
		catch
		{(Exception e)
	
		
		
	
	
	


